### PR TITLE
Updates to README.md

### PR DESCRIPTION
**Pull request by lanhamm**
Updates for readability and clarity

I had trouble following some of the directions as they were written, so my edits are to try to make them more clear for the next people who try to use them.

### CODE REVIEW

**Comment by lanhamm** [comment]
Thank you for this plug-in!

**Comment by eduard93** [comment]
Hello.  Thank you for your contribution!

1. Please correct the numbering in the README. Here's screenshot off your [pull](https://github.com/intersystems-ru/cache-tort-git/pull/48/commits/3d48e7604bdf5429efcc22b65b16f88b93a6b78d):
image

Old numbering (everywhere) was 1,2,3... now its (also everywhere) 1,1,1...

2. In the section`Installation in Caché`: 
  - `CACHELIB namespace` should be `CACHELIB database`
  - `%CACHELIB database` should be `CACHELIB database`
- '%CACHELIB' should be `CACHELIB`

**Comment by lanhamm** [comment]
Hi - you're actually not using markdown appropriately by numbering things 1, 2, 3.  Look at the preview and you'll see that it looks correct when you use 1, 1, 1. [See documentation here.](https://guides.github.com/features/mastering-markdown/)

I made the CACHELIB changes.

Thanks,
Michael

**Comment by eduard93** [comment]
Didn't knew about numbering by 1,1,1. Still 1,2,3 produces the same result but looks nicer in my opinion. @adaptun?

**Comment by eduard93** [comment]
Also `CACHELIB namespace` should be `CACHELIB database`. There's no `CACHELIB namespace`.

**Pull request merged**
